### ISSUE TITLE
add data backend for scaling and data persistence support

### ISSUE THREAD

**Issue by jcuga** [jcuga/golongpoll#10]
Currently event buffers are all in-memory--in many ways this is a performance gain and is simpler code.

However, if you want the event buffer to persist across restarts, or to load balance across multiple instances, data(base) backend support would be useful.

My current workaround for scaling is to design data needs up front to be deterministic so I can segment traffic consistently to the same running instance and each instance has it's own sub-universe of data.  There is no workaround for persisting data across program restarts 😢 

At some point I will try and add support for data backends, but cannot promise when that will be.

**Comment by valichek** [comment]
I think the best idea is to create connector to existing things. NATS could be a good example of message bus.

**Comment by jcuga** [comment]
v2.0.0 adds [AddOn interface](https://github.com/jcuga/golongpoll/blob/master/addons.go) and `golongpoll.Options.AddOn` to provide hooks to add custom behavior.  Additionally, [FilePersistorAddOn](https://github.com/jcuga/golongpoll/blob/master/fileaddon.go) provides event persistence to file.  See the [filepersist example](https://github.com/jcuga/golongpoll/blob/master/examples/filepersist/filepersist.go).

Additional scaling can be accomplished by having more than one LongpollManager (created by `golongpoll.StartLongpoll()`) and by how one designs the use of categories.  Scaling within an individual `LongpollManager` is beyond the scope of this library and will likely never be addressed.
