### ISSUE TITLE
High CPU load?

### ISSUE THREAD

**Issue by andig** [jcuga/golongpoll#15]
I'm using this library for publishing events of multiple connected meters (constantly being polled at 9600 baud). I've noticed that just publishing those events longpoll manager- even without connected clients- raises CPU load to > 50% on Raspi3:

    func (f *Firehose) Run() {
        for {
            select {
            case snip := <-f.in:
                f.lpManager.Publish("meterupdate", snip)
            case statupdate := <-f.statstream:
                f.lpManager.Publish("statusupdate", statupdate)
            }
        }
    }
    ...
    go firehose.Run()

Does this behaviour make sense to you or should a low CPU load be expected when publishing without clients attached?

**Comment by jcuga** [comment]
Can you show how you created the long poll manager, namely how it was configured—or if it’s the default options.  Then I can try and diagnose.

Also, how much data, what approx size, approx rates for calling publish, and how many different categories are you publishing on?

Thanks for using the library!

**Comment by jcuga** [comment]
The CPU load not going down when there are no clients subscribed is not surprising, as the longpollManager will buffer events for each category when Publish() is called--with the precise behaviour dictated by the configuration.  So the default config has a buffer of 250 events and an event expire of "forever."  So essentially it will always buffer the latest 250 events for each category.  This is done even when no clients are connected.  This buffering is done via a priority queue / tree per category organized by publish time. 

If clients are not interested in old events, I could add an option where it doesn't start buffering events for a given category unless there has been a client subscribed to the given category within the last N (milli)seconds.  Currently it will always buffer even without an active subscription.  The erring on the side of buffering is mainly motivated by the following scenario:

A client subscribes (http GET the subscription handler), gets a response back with data.  Client does a GET again to continue getting more events.  But there is a small amount of time between when the first events request was returned and before the client completes the second subscription request that events may have occurred.  So in this case the buffering would catch these events and the client would get them on the second GET.  But if there has never been a client subscribed to a category, or at least not for quite some time, then this buffering is not preventing any gaps in data that the above scenario was concerned about.

So my question would be:  do you have periods of time where there are no client subscriptions where an option like this would prevent wasting as much CPU?  Or will you always have clients subscribed?

Either way, I can look into adding this option and seeing if it helps.  While I'm in there I can see if there are any other inefficiencies that can be improved in the case where clients will be subscribed and we can't take advantage of this new option.  I will likely have time to work on this in 1-2 weeks.

**Comment by andig** [comment]
Thank you for the detailed explanation. 

> So my question would be: do you have periods of time where there are no client subscriptions where an option like this would prevent wasting as much CPU? Or will you always have clients subscribed?

It depends. One use case is serving the internal web UI with data. Most often the UI will not be open in any browser and no client connected. 

> Either way, I can look into adding this option and seeing if it helps.

For this particular case I've already changed the logic from longpolling to websockets which seems more appropriate and is drastically reducing load. From my side not update needed.

> The CPU load not going down when there are no clients subscribed is not surprising, ...  the default config has a buffer of 250 events and an event expire of "forever."

I'm still surprised that buffering 250 events for essentially a single hard-hit topic is that expensive. Apart from already having an alternative on my side- is there a possible problem with the way the underlying queue???

**Comment by jcuga** [comment]
I am currently working on v2.0 changes for this library and have noticed that there are some unnecessary copying of event data.  This was due to using `Event` instead of `*Event` internally in a few places.  These changes should help at least a little bit.

This is fixed in commit 3e085353319ec897e088b0a92d79d496a00d3433

I will have to do some profiling to see if I discover any more issues as well.
