### ISSUE TITLE
client js

### ISSUE THREAD

**Issue by bluebrown** [jcuga/golongpoll#17]
Hello,

I really like the project, and I am using it for some internal tools. I wanted to share the little js client "library" I have created over the weekend. Maybe you can use it.

https://gist.github.com/bluebrown/53e5144ea5c7e8fb1c77c20187844273

Anyway, thank you for the package.

Regards,
Nico

**Comment by jcuga** [comment]
@bluebrown thanks for sharing.  I plan on doing some major updates to this library and plan on providing an "official" javascript library.  This will certainly help on that end as I'm not a javascript ninja (TM)  these days.

**Comment by bluebrown** [comment]
Hi no problem.  If I can help somehow with the JS, I would be happy to. Its been a while since a wrote  I bet there is lots of room for improvement.

**Comment by jcuga** [comment]
I added an official js client [here](https://github.com/jcuga/golongpoll/tree/master/js-client).

This is admittedly not very modern looking javascript.  If you want to embellish it but keep similar behavior/rigor (or more) and create an actual npm package or something I would be interested in that.
