### ISSUE TITLE
How do you make sure the concurrent issue?

### ISSUE THREAD

**Issue by dawei101** [jcuga/golongpoll#25]
https://github.com/jcuga/golongpoll/blob/033d1fa3098d8aed25a1f9dd9a02df93341de62a/longpoll.go#L652

I see there is  no lock when remove and add item from map, this will case crash.

**Comment by jcuga** [comment]
Hello,

I believe the map usage is always run in the same goroutine, which uses channels to receive actions from the http goroutintes.  This is the subscription manager's run() function running in it's own goroutine.

See:
https://github.com/jcuga/golongpoll/blob/72ba13b6b436636c2cca5e916840694fa2c38a39/longpoll.go#L282
```
	go subManager.run()
```

Where the run function has:
https://github.com/jcuga/golongpoll/blob/72ba13b6b436636c2cca5e916840694fa2c38a39/longpoll.go#L531
```
		select {
		case newClient := <-sm.clientSubscriptions:
			sm.handleNewClient(newClient)
			sm.seeIfTimeToPurgeStaleCategories()
		case disconnected := <-sm.ClientTimeouts:
			sm.handleClientDisconnect(disconnected)
			sm.seeIfTimeToPurgeStaleCategories()
		case event := <-sm.Events:
			// Optional hook on publish
			if sm.AddOn != nil {
				sm.AddOn.OnPublish(event)
			}
			sm.handleNewEvent(event)
			sm.seeIfTimeToPurgeStaleCategories()
```

Then, when other goroutines handling HTTP need to tell the subscription manager about a new client, a new event, or a disconnect, they send data to the manager via channels which are concurrent-safe.

for example:
sending new subscription over channel to run():
https://github.com/jcuga/golongpoll/blob/72ba13b6b436636c2cca5e916840694fa2c38a39/longpoll.go#L444

client disconnect:
https://github.com/jcuga/golongpoll/blob/72ba13b6b436636c2cca5e916840694fa2c38a39/longpoll.go#L474

event publish:
https://github.com/jcuga/golongpoll/blob/72ba13b6b436636c2cca5e916840694fa2c38a39/longpoll.go#L90


Conversely, the manager's goroutine will send data back to clients via channels:
https://github.com/jcuga/golongpoll/blob/72ba13b6b436636c2cca5e916840694fa2c38a39/longpoll.go#L619


If you see any code that is accessing maps across multiple goroutines, or if you have encountered any errors, please point them out and I will try to fix them.  But I think all map access is limited to the manager's run() goroutine and the functions called by run()  which are still within the same goroutine.  All cross-go-routine sharing of data is done via channels.

**Comment by dawei101** [comment]
Thanks for so rich reply, get it 💯
