### ISSUE TITLE
Gin framework support

### ISSUE THREAD

**Issue by hims1911** [jcuga/golongpoll#26]
Do you guys have any idea or plan for GIN package support for long polling? I would love to work on the same.

Thanks.

**Comment by GwynethLlewelyn** [comment]
(Good, I'm so glad I'm not the only one thinking about the same!)

Er, +1 on this issue/question/suggestion!

**Comment by jcuga** [comment]
I haven't used gin but I plan on taking a look into what sort of lift this would entail. Stay tuned!

**Comment by jcuga** [comment]
From a quick glance, I believe one can do the following with golongpoll + gin:

```go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/jcuga/golongpoll"
)

func main() {
	// Create longpoll manger with default opts
	manager, err := golongpoll.StartLongpoll(golongpoll.Options{})
	if err != nil {
		panic(err)
	}

	router := gin.Default()
	router.POST("/pub", wrapWithContext(manager.PublishHandler))
	router.GET("/sub", wrapWithContext(manager.SubscriptionHandler))
	router.Run(":8001")
}

func wrapWithContext(lpHandler func(http.ResponseWriter, *http.Request)) func(*gin.Context) {
	return func(c *gin.Context) {
		lpHandler(c.Writer, c.Request)
	}
}
```

This will let you stick the longpoll pub/sub handlers within a `router.POST` and `router.GET` handler.

Is this what you wanted, or something more?

I could make a `gin-longpoll` repo that provides some convenience functions for doing this... Is there anything more to it than this?

**Comment by jcuga** [comment]
I wonder if the above example would "just work" with any of gin middleware before/after it gets to the pub/sub handlers.  I'd imagine it should?

**Comment by hims1911** [comment]
@jcuga thanks for the solution which you've provided. I think its better if we create a separate repo so that later people can add more issues and enhancements to the same.



> I wonder if the above example would "just work" with any of gin middleware before/after it gets to the pub/sub handlers. I'd imagine it should?

let me try I will update you on this.

**Comment by jcuga** [comment]
I added the above gin example to the readme in [958739a](https://github.com/jcuga/golongpoll/commit/958739a076415aaee9ffddce3521c4659f9223b9)

**Comment by jcuga** [comment]
Closing as README now has example of using with gin via: [958739a](https://github.com/jcuga/golongpoll/commit/958739a076415aaee9ffddce3521c4659f9223b9)
