### ISSUE TITLE
Acks every 15 seconds

### ISSUE THREAD

**Issue by dimalukas** [jcuga/golongpoll#28]
Hi,
While I was monitoring network traffic on my device I saw that every 15 seconds there are acks being sent between the longpoll client and server.
Is this the intentional behavior?
The activity does not need to be ‘silent’ until a timeout occurs or a disconnect or a publish?
@jcuga 
![D7BF0ED5-EA28-4574-9534-F433102B58DF](https://user-images.githubusercontent.com/7952328/178929346-c1ef6445-6775-4f64-a18b-1748b7015d99.jpeg)

**Comment by jcuga** [comment]
@dimalukas this sounds like tcp keepalive.

See: https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html

This occurs at the TCP/transport level, before the HTTP/application level.  So there will be no http data being sent, but you will see at the lower TCP level some zero-data ACKs that are part of the tcp-keepalive.  The keep alive time is configurable usually at the OS level, not at a per-socket or per-application level.

Without keep-alives, there'd be no way for each side of the connection to know when a connection gets dropped.


This occurs at a lower, more fundamental level than HTTP and golongpoll specifically.  I'd recommend looking at the traffic in wireshark or similar tool to verify that this is indeed zero-data keepalive traffic if you are concerned.

To your question about being "silent" until there is data (or a longpoll-timeout)--at the HTTP/application level, yes, there should be no data/communication.
