### ISSUE TITLE
Return timestamp in timeout response

### ISSUE THREAD

**Issue by fabioxgn** [jcuga/golongpoll#3]
I can implement it if it makes sense.

I have an application that can be offline sometimes, so I'm passing the timestamp to get past events, but in this scenario it fails:

- The application starts and connects to the server, there is no event, so it gets one or more timeouts.
- Then the connection drops and while the client is offline the server receives some new events.
- When the client reconnects, there is no events as it did not pass a `since_time` value because it didn't have a timestamp from the last event (as it did not receive any).

I could calculate the timestamp on the client, but I don't think it would solve this, the date/time of the client could be wrong for example.

It would work better if the timeout reply returned a timestamp, in this case:

```JSON
{
  "timeout": "no events before timeout",
  "timestamp": 1447218359843
}
```

Then I could update the timestamp after the first timeout, and even if the client loses the connection It will be able to get past events since the last timeout.

What do you think?

**Comment by jcuga** [comment]
So if I understand correctly, the timestamp returned on the timeout response is just the current server time when the timeout occurred?  Seems perfectly fine to me.  If you want to make then change feel free, otherwise i can go ahead and add it within the next day or so.

**Comment by fabioxgn** [comment]
@jcuga yes, the current timestamp when the timeout ocurred.

**Comment by jcuga** [comment]
working on adding this...

**Comment by jcuga** [comment]
@fabioxgn this should be accomplished via e46890306d0f3166bb38b93da9445f1c6118358f

Let me know if this is satisfactory. 

Thanks!

**Comment by fabioxgn** [comment]
@jcuga thanks! That will work for me.
