### ISSUE TITLE
Latest tag name seems like a typo - messes up SemVer

### ISSUE THREAD

**Issue by activeshadow** [jcuga/golongpoll#6]
Latest tag is `v.1.1.0`, and I think it should be `v1.1.0`. Having it as `v.1.1.0` messes up SemVer support with package managers like Glide.

Can you retag?

**Comment by jcuga** [comment]
I have re-tagged:   https://github.com/jcuga/golongpoll/tree/v1.1.0

Thanks for the catch.  This also forced me to pick up this project again and fix some test failures that were exposed by go1.7 behavior.  All fixed.

**Comment by activeshadow** [comment]
Thank you.

Yes... I too now have a lot of code to test and update due to go1.7 release.
