### ISSUE TITLE
used in production?

### ISSUE THREAD

**Issue by notedit** [jcuga/golongpoll#8]
do golongpoll has some  success in production?

**Comment by jcuga** [comment]
I've personally seen it used for private chat servers (think like Reddit but with immediate updates/chat) with ~5 users running for weeks without any issues.  This runs on the equivalent of a tiny aws instance (minimal ram/cpu).

Aside from that I couldn't tell you.  Though this repo has been cloned hundreds of times so somebody is using it :)
